### ISSUE TITLE
Departman ve Birim Oluşturma Sayf. 

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#24]
Bu sayfalardaki güncelle butonuna eklediğim data-user="" kısmına eğer müdür veya yöneticisi varsa ismi gelmesi lazım. Mesela şuan şöyle gözüküyor. [http://prntscr.com/di36f8](http://prntscr.com/di36f8)

**Comment by OkanUzun** [comment]
düzeltildi
