### ISSUE TITLE
Eğitim oluşturma sayfası

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#30]
Eğitim oluştururken tarih in yanı sıra saatin de seçilmesi gerekiyor. Bunun için [https://eonasdan.github.io/bootstrap-datetimepicker/](https://eonasdan.github.io/bootstrap-datetimepicker/) bu plugin kullanılabilir.

**Comment by OkanUzun** [comment]
Yapıldı
