### ISSUE TITLE
Eğitim oluşturma sayfası (eğitim salonu)

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#31]
Eğitim oluştururken eğitim salonunun nerede olduğu bilgisi de alınacak.

**Comment by OkanUzun** [comment]
Salon seçiniz dropdown u eğitim adının altında olsun. Hepsi yan yana olmuş pek iyi görünmüyor.

**Comment by denizmaradona** [comment]
Son hali kalsın böyle
