### ISSUE TITLE
Yetenek tablosu, B planı

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#32]
Yetenek tablosundaki sil/ekle linkleri submit button a çevrilebilir.

**Comment by OkanUzun** [comment]
Butonları submit butona çevirir misin ayrıca sol taraftaki tablolara sil butonuna ek olarak güncelle butonu da eklemek lazım yetenek seviyesini güncellemek için.

**Comment by denizmaradona** [comment]
Butonlar submit şekilde düzeltildi
