### ISSUE TITLE
Eğitim oluşturma - Timepicker

### ISSUE THREAD

**Issue by OkanUzun** [OkanUzun/Rol-ve-Yetenek-Uyg.#33]
Zaman formatlarının gün ay yıl formatı şu şekilde olmalı saat formatında değişiklik yapmana gerek yok
Örnek : 22.12.2016 ya da 22-12-2016

Türkçe ay ismi sorun çıkartıyor.
Düzeltmeden sync edersin.

**Comment by denizmaradona** [comment]
Düzeltildi
