### ISSUE TITLE
course-detail.php saat ve dakikanın 00:00 olarak gösterilmesi

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#34]
Bu sayfada tarihin yanında saat yanlış basılıyor

**Comment by OkanUzun** [comment]
db den saat doğru geliyor ama saati algılamıyor. input içinde gösterimden kaynaklı normal gösterimde herhangi bir sorun olmuyor.

**Comment by denizmaradona** [comment]
Düzeltildi
