### ISSUE TITLE
Şifre değiştirme sayfası

### ISSUE THREAD

**Issue by OkanUzun** [OkanUzun/Rol-ve-Yetenek-Uyg.#37]
Şifre değiştirme olayının mantığını değiştirdim. Kullanıcı emailini şifremi unuttum kısmına girdikten sonra kendi mailine şifre sıfırlama bağlantısı gelecek ve o bağlantıdan şifresini değiştiricek. Bunun için yeni bir sayfa gerekli, input olarak email ve iki kez password alacak.

**Comment by denizmaradona** [comment]
Oluşturuldu
