### ISSUE TITLE
sidebar.php active link

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#39]
Sidebardaki li'lere bulunduğu sayfaya göre active class'ı atanıp silinmeli

**Comment by OkanUzun** [comment]
Niye böyle birşey yapıyoruz?

**Comment by denizmaradona** [comment]
O an bulunulan sayfa solda yeşil renk olacak. ana sayfa şuan yeşil mesela active class ı olduğu için. çok uğraştırcaksa sıkıntı değil kaldırırım

**Comment by OkanUzun** [comment]
düzeltildi
