### ISSUE TITLE
Şifre sıfırlama bağlantısı

### ISSUE THREAD

**Issue by OkanUzun** [OkanUzun/Rol-ve-Yetenek-Uyg.#42]
Maile gelen bağlantı link olarak gözükmüyor.

**Comment by denizmaradona** [comment]
Çalışıyor sıkıntı yok

**Comment by denizmaradona** [comment]
Fakat mailde kullanıcının ismi yazmıyor şuan

**Comment by OkanUzun** [comment]
bende böyle gözüküyor
![screenshot_1](https://cloud.githubusercontent.com/assets/12533333/21733855/41d0018a-d469-11e6-967e-8e18354b0e83.png)

**Comment by denizmaradona** [comment]
Düzeltildi
