### ISSUE TITLE
Course-detail.php eğitimci güncelleme

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#45]
Şirket içi eğitimci tanımladım eğitimi oluştururken. Sonra eğitimciyi şirket dışı tanımladığım birine güncellediğimde toast mesajında eğitim güncellendi diyor fakat eğitimci güncellenmiyor.

**Comment by OkanUzun** [comment]
düzeltildi
