### ISSUE TITLE
Grafikler - Responsive

### ISSUE THREAD

**Issue by OkanUzun** [OkanUzun/Rol-ve-Yetenek-Uyg.#48]
![screenshot_1](https://cloud.githubusercontent.com/assets/12533333/21750159/62b5e3ae-d5b5-11e6-9085-abe50315b845.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12533333/21750160/661f1718-d5b5-11e6-9c26-c81555f7e0c1.png)

Grafiği doğru gösteriyor ama altındaki yazıyla uyuşmuyor

**Comment by OkanUzun** [comment]
Bir de soldaki sayılar tam sayı olmalı

**Comment by denizmaradona** [comment]
Düzeltildi
