### ISSUE TITLE
Db ye gönderilen verilerin kontrolü

### ISSUE THREAD

**Issue by denizmaradona** [OkanUzun/Rol-ve-Yetenek-Uyg.#5]
Gönderilen verilerin başarılı ya da başarısız olup olmadığına göre pop-up/modal/toast tarzı bir şey yapılabilir.

**Comment by OkanUzun** [comment]
sade bir bilgilendirme olsun modal kullanmaya gerek yok toast yada pop-up olabilir.

**Comment by denizmaradona** [comment]
Bilgilendirme için toast mesajları eklendi, eklenmeyen yerler var user-create, course-create gibi

**Comment by denizmaradona** [comment]
Tüm db mesajları için toastlar eklendi.
